### ISSUE TITLE
Broken on OS X

### ISSUE THREAD

**Issue by alxlu** [MicrosoftEdge/hwa-cli#1]
It looks like the line endings this is saved to npm with (CRLF) have some issues on OS X:
<img width="1102" alt="image1447687549307" src="https://cloud.githubusercontent.com/assets/3271834/11187979/9224bba0-8c3d-11e5-99c6-2aab3f1b9e70.png">
I manually fixed the line endings, but it seems to randomly get errors during image conversion and fail. I suspect some of these errors will happen on Windows as well (will follow up to confirm).

If there aren't any image conversion errors, it doesn't launch phantomjs and just hangs.

Also, running just `hwa` fails because the tool can't find the documentation.

Was running NodeJS 5.0 and npm 3.3.9

**Comment by zackhall** [comment]
The line endings issue has been fixed by adding the .gitattributes file to enforce line endings and enforcing line endings in the typescript compiler.

Now on OSX I'm seeing the other two issues mentioned by Alex. Here are the issues, neither repros on Windows:
* Running `hwa` can't find the documentation.
* Running `hwa convert path/to/package.crx` hangs on the image conversion.
